### ISSUE TITLE
a highly possible error in "benchmarktu1402.py" script

### ISSUE THREAD

**Issue by Negin-Mashhadi** [ETH-WindMil/benchmarktu1402#2]
Thank you for the incredible code! It has been a great help for me, however, I think this could be fixed if we want the file to save the pre-defined Beta parameter.
line 1655 in "benchmarktu1402.py" script :
beta.insert(tk.END, self.main.job.timeHistorySettings['Alpha'])
 
should be changed to :
beta.insert(tk.END, self.main.job.timeHistorySettings['Beta']
![Capture](https://user-images.githubusercontent.com/73463347/170863739-da1b9467-e078-4e87-b9d5-bde2b399119c.PNG)

**Comment by os-kon** [comment]
Thank you for creating this issue, which is now fixed.
